org.gradle.jvmargs=-Xmx4096m
org.gradle.parallel=true
org.gradle.configureondemand=true
android.useAndroidX=true
android.enableJetifier=true
FLIPPER_VERSION=0.182.0
ReactNativeArchitectures=arm64-v8a,armeabi-v7a
newArchEnabled=false
hermesEnabled=true
org.gradle.java.home=/Applications/Android Studio.app/Contents/jbr/Contents/Home
android.suppressUnsupportedCompileSdk=35
